# agent_workflow.py
import logging
from langgraph.graph import StateGraph, END
from typing import TypedDict
from flask import Flask, request, jsonify
import nltk
import os

from .helper_functions import (
    retrieve_context_per_question,
    keep_only_relevant_content,
    answer_question_from_context,
)

# Set up Flask app
app = Flask(__name__)

# Download required nltk data
data_dir = os.path.join(os.getcwd(), "nltk_data")
nltk.download('stopwords', download_dir=data_dir)
nltk.download('wordnet', download_dir=data_dir)

# Set up basic logging
logging.basicConfig(level=logging.INFO)

# Define the workflow data structure
class PlanExecute(TypedDict):
    question: str
    context: str
    relevant_context: str
    answer: str

# Initialize state graph workflow variables
state_graph_workflow = None
compiled_workflow = None

# Create and initialize the state graph
def create_workflow():
    global state_graph_workflow, compiled_workflow

    logging.info("Initializing StateGraph...")

    try:
        # Create the workflow
        state_graph_workflow = StateGraph(PlanExecute)
        logging.info(f"Workflow initialized successfully. Type of state_graph_workflow: {type(state_graph_workflow)}")

        # Add nodes to the workflow
        state_graph_workflow.add_node("retrieve_context", retrieve_context_per_question)
        logging.info("Added node 'retrieve_context'.")

        state_graph_workflow.add_node("filter_content", keep_only_relevant_content)
        logging.info("Added node 'filter_content'.")

        state_graph_workflow.add_node("generate_answer", answer_question_from_context)
        logging.info("Added node 'generate_answer'.")

        # Define the edges (transitions) between nodes
        state_graph_workflow.set_entry_point("retrieve_context")
        logging.info("Set entry point to 'retrieve_context'.")

        state_graph_workflow.add_edge("retrieve_context", "filter_content")
        state_graph_workflow.add_edge("filter_content", "generate_answer")
        state_graph_workflow.add_edge("generate_answer", END)
        logging.info("Defined edges successfully.")

        # Compile the workflow
        compiled_workflow = state_graph_workflow.compile()
        logging.info(f"Workflow compiled successfully. Type of compiled_workflow: {type(compiled_workflow)}")

    except Exception as e:
        logging.error(f"Error while initializing StateGraph: {e}")

# Initialize the workflow
create_workflow()

# Plan and execute function
def plan_and_execute_app(inputs):
    logging.info(f"Received inputs for planning: {inputs}")

    if compiled_workflow is None:
        logging.error("Compiled workflow is None. Ensure that create_workflow() was called.")
        return {"error": "Workflow is not properly initialized."}

    # Debug log the type of compiled_workflow
    logging.info(f"Executing compiled_workflow. Type of compiled_workflow: {type(compiled_workflow)}")

    # Attempt to invoke the workflow using the correct method
    try:
        output = compiled_workflow.invoke(inputs)
        logging.info(f"Output generated by plan_and_execute_app using compiled_workflow: {output}")

        # Ensure output is serializable
        if isinstance(output, dict):
            return output
        else:
            logging.error("Output is not in expected dictionary format.")
            return {"error": "Unexpected output format from workflow."}

    except TypeError as e:
        logging.error(f"Type error during plan_and_execute_app: {e}")
        return {"error": f"Type error: {str(e)}"}
    except Exception as e:
        logging.error(f"Unexpected error during plan_and_execute_app: {e}")
        return {"error": f"Unexpected error: {str(e)}"}

# Flask route to interact with the workflow
@app.route('/chatbot/chatgpt', methods=['POST'])
def chatbot_endpoint():
    try:
        data = request.get_json()
        logging.info(f"Received data from client: {data}")

        question = data.get("question")
        if not question:
            return jsonify({"error": "Question not provided."}), 400

        inputs = PlanExecute(question=question, context="", relevant_context="", answer="")
        response = plan_and_execute_app(inputs)

        # Ensure the response is JSON serializable
        if isinstance(response, dict):
            return jsonify(response)
        else:
            return jsonify({"error": "Unexpected output format from workflow."}), 500

    except Exception as e:
        logging.error(f"Error in chatbot_endpoint: {e}")
        return jsonify({"error": f"Unexpected error: {str(e)}"}), 500

# Main entry point
if __name__ == '__main__':
    app.run(debug=False, host='127.0.0.1', port=5000)
